version: "3.5"
services:
  backend:
    build: myapi/
    image: 'backend'
    container_name: backend
    ports:
      - "1150:80"
    links:
      - "database:database"
    network_mode: bridge
    depends_on:
      - database
  frontend:
    build: mypos/
    image: 'frontend'
    container_name: frontend
    ports:
      - "2234:80"
    network_mode: bridge
    depends_on:
      - backend
  database:
    image: "mcr.microsoft.com/mssql/server:2017-CU14-ubuntu"
    container_name: cm_database
    environment:
      SA_PASSWORD: "Tel1234!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    network_mode: bridge